/**
 * Test script for TutorBot Plus API endpoints
 * Run with: npx tsx test-api.ts
 */

import { prisma } from './lib/prisma';
import { addCredits, getUserCredits, deductCourseCreationCredits } from './lib/credits';

async function main() {
  console.log('🧪 Testing TutorBot Plus API...\n');

  // 1. Create a test user
  console.log('1️⃣  Creating test user...');
  const testUser = await prisma.user.upsert({
    where: { email: 'test@tutorbot.com' },
    update: {},
    create: {
      email: 'test@tutorbot.com',
      name: 'Test User',
      credits: 0,
    },
  });
  console.log(`✅ Test user created: ${testUser.email} (ID: ${testUser.id})\n`);

  // 2. Grant initial credits
  console.log('2️⃣  Granting 100 credits...');
  await addCredits(testUser.id, 100, 'PROMOTIONAL_GRANT', 'Test credits');
  const balance = await getUserCredits(testUser.id);
  console.log(`✅ Credits granted. Balance: ${balance}\n`);

  // 3. Create a test course
  console.log('3️⃣  Creating a Math course...');
  const course = await prisma.course.create({
    data: {
      userId: testUser.id,
      title: 'Introduction to Algebra',
      subject: 'math',
      level: 'beginner',
      description: 'Learn the fundamentals of algebra including variables, equations, and problem-solving.',
    },
  });
  console.log(`✅ Course created: "${course.title}" (ID: ${course.id})\n`);

  // 4. Create lessons for the course
  console.log('4️⃣  Creating lessons...');
  const lesson1 = await prisma.lesson.create({
    data: {
      courseId: course.id,
      title: 'What are Variables?',
      content: 'Placeholder content - to be generated by AI',
      order: 1,
    },
  });

  const lesson2 = await prisma.lesson.create({
    data: {
      courseId: course.id,
      title: 'Solving Simple Equations',
      content: 'Placeholder content - to be generated by AI',
      order: 2,
    },
  });
  console.log(`✅ Created 2 lessons\n`);

  // 5. Test credit deduction
  console.log('5️⃣  Testing credit deduction...');
  const beforeBalance = await getUserCredits(testUser.id);
  await deductCourseCreationCredits(testUser.id, 'Test Course', { test: true });
  const afterBalance = await getUserCredits(testUser.id);
  console.log(`✅ Credits deducted: ${beforeBalance} → ${afterBalance} (spent 50)\n`);

  // 6. Get courses with progress
  console.log('6️⃣  Fetching user courses...');
  const courses = await prisma.course.findMany({
    where: { userId: testUser.id },
    include: {
      _count: {
        select: { lessons: true },
      },
      lessons: {
        select: {
          id: true,
          title: true,
          order: true,
        },
        orderBy: { order: 'asc' },
      },
    },
  });
  console.log(`✅ Found ${courses.length} course(s):`);
  courses.forEach((c) => {
    console.log(`   📚 ${c.title} - ${c.subject} (${c.level})`);
    console.log(`      Lessons: ${c._count.lessons}`);
    c.lessons.forEach((l) => {
      console.log(`      ${l.order}. ${l.title}`);
    });
  });
  console.log();

  // 7. Summary
  console.log('📊 Test Summary:');
  console.log(`   User: ${testUser.email}`);
  console.log(`   User ID: ${testUser.id}`);
  console.log(`   Credits: ${afterBalance}`);
  console.log(`   Courses: ${courses.length}`);
  console.log(`   Lesson 1 ID: ${lesson1.id}`);
  console.log(`   Lesson 2 ID: ${lesson2.id}`);
  console.log();
  console.log('✅ All database operations successful!');
  console.log();
  console.log('🔗 Next steps:');
  console.log(`   1. Test lesson generation: POST /api/lessons/${lesson1.id}/generate`);
  console.log(`   2. Test course API: GET /api/courses`);
  console.log(`   3. Add OPENAI_API_KEY to .env for AI generation`);
}

main()
  .catch((error) => {
    console.error('❌ Test failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
