'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface Lesson {
  id: string;
  title: string;
  content: string;
  videoUrl?: string;
  duration?: number;
  completed: boolean;
  order: number;
  quiz?: {
    id: string;
    passingScore: number;
  };
}

interface LessonViewerProps {
  lesson: Lesson;
  courseId: string;
  userCredits?: number;
  onGenerateContent?: () => void;
  onTakeQuiz?: () => void;
  onComplete?: () => void;
}

export function LessonViewer({
  lesson,
  courseId,
  userCredits = 0,
  onGenerateContent,
  onTakeQuiz,
  onComplete,
}: LessonViewerProps) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [lessonContent, setLessonContent] = useState(lesson.content);
  const [hasQuiz, setHasQuiz] = useState(!!lesson.quiz);

  const GENERATION_COST = 10;
  const canAfford = userCredits >= GENERATION_COST;
  const hasContent = lessonContent && lessonContent !== 'Placeholder content - to be generated by AI';

  const handleGenerateContent = async () => {
    if (!canAfford) {
      setError(`Insufficient credits. You need ${GENERATION_COST} credits to generate lesson content.`);
      return;
    }

    setError('');
    setGenerating(true);

    try {
      const response = await fetch(`/api/lessons/${lesson.id}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          generateQuiz: true,
          quizQuestions: 5,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate content');
      }

      setLessonContent(data.lesson.content);
      if (data.quiz) {
        setHasQuiz(true);
      }

      if (onGenerateContent) {
        onGenerateContent();
      }
    } catch (err: any) {
      setError(err.message || 'Failed to generate content');
    } finally {
      setGenerating(false);
    }
  };

  const handleMarkComplete = () => {
    if (onComplete) {
      onComplete();
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Lesson Header */}
      <Card className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-2">
              <Badge variant={lesson.completed ? 'default' : 'secondary'}>
                Lesson {lesson.order}
              </Badge>
              {lesson.completed && (
                <Badge className="bg-green-500">
                  ✓ Completed
                </Badge>
              )}
              {hasQuiz && (
                <Badge className="bg-blue-500">
                  📝 Quiz Available
                </Badge>
              )}
            </div>
            <h1 className="text-3xl font-bold text-gradient-hero">{lesson.title}</h1>
            {lesson.duration && (
              <p className="text-gray-600 mt-2">
                Estimated time: {lesson.duration} minutes
              </p>
            )}
          </div>
        </div>

        {/* Generate Content Button */}
        {!hasContent && (
          <div className="mt-4 p-4 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-sm text-amber-800 mb-3">
              This lesson content hasn't been generated yet. Generate it with AI to start learning!
            </p>
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">
                Cost: {GENERATION_COST} credits
              </span>
              <Button
                onClick={handleGenerateContent}
                disabled={generating || !canAfford}
                className="bg-gradient-primary text-white"
              >
                {generating ? (
                  <span className="flex items-center">
                    <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Generating...
                  </span>
                ) : (
                  `Generate Content (${GENERATION_COST} credits)`
                )}
              </Button>
            </div>
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
            {error}
          </div>
        )}
      </Card>

      {/* Video Player (if available) */}
      {lesson.videoUrl && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold mb-4">Video Lesson</h2>
          <div className="aspect-video bg-gray-100 rounded-lg flex items-center justify-center">
            <p className="text-gray-500">Video player placeholder: {lesson.videoUrl}</p>
          </div>
        </Card>
      )}

      {/* Lesson Content */}
      {hasContent && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold mb-4">Lesson Content</h2>
          <div
            className="prose prose-blue max-w-none"
            dangerouslySetInnerHTML={{
              __html: lessonContent
                .replace(/\n/g, '<br/>')
                .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                .replace(/\*(.*?)\*/g, '<em>$1</em>')
            }}
          />
        </Card>
      )}

      {/* Action Buttons */}
      {hasContent && (
        <Card className="p-6">
          <div className="flex gap-4 justify-between items-center">
            <div>
              {hasQuiz ? (
                <p className="text-sm text-gray-600">
                  Ready to test your knowledge? Take the quiz to complete this lesson.
                </p>
              ) : (
                <p className="text-sm text-gray-600">
                  Mark this lesson as complete when you're ready to move on.
                </p>
              )}
            </div>
            <div className="flex gap-3">
              {hasQuiz && (
                <Button
                  onClick={onTakeQuiz}
                  className="bg-blue-500 hover:bg-blue-600 text-white"
                >
                  📝 Take Quiz
                </Button>
              )}
              {!lesson.completed && (
                <Button
                  onClick={handleMarkComplete}
                  className="bg-green-500 hover:bg-green-600 text-white"
                >
                  ✓ Mark Complete
                </Button>
              )}
            </div>
          </div>
        </Card>
      )}

      {/* Navigation Hint */}
      <div className="text-center text-sm text-gray-500">
        <p>Use the sidebar to navigate between lessons</p>
      </div>
    </div>
  );
}
